tasks:
- name: docker-install
  init: |
    docker-compose pull
    gp sync-done docker
  command: |
    docker-compose up

- name: wordpress-install
  # Waits a little and then configures Wordpress
  # More wp-cli commands are possible following "docker exec -it gitpod-wordpress-development-wordpress-1" and ending with "--allow-root"
  # Last line opens Website in new browser window
  init: |
    gp sync-await docker
    echo "Waiting 20s for DB to get ready..."
    sleep 20
    docker exec -it gitpod-wordpress-development-wordpress-1 wp core install --url="8000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}" --title="Gitpod Wordpress Development" --admin_user="admin" --admin_password="admin" --admin_email="you@example.com" --allow-root
  # Set permission that "gitpod" user can access folders created inside docker container. Couldn't find a better way.
  # Then open Wordpress in Browser
  command: |
      chmod -R 755 ./wp-core
      chmod -R 755 ./wp-content/plugins
      chmod -R 755 ./wp-content/themes
      chown -R gitpod:gitpod ./wp-core
      chown -R gitpod:gitpod ./wp-content/plugins
      chown -R gitpod:gitpod ./wp-content/themes
      gp preview $(gp url 8000) --external


ports:
  - port: 8000
    onOpen: ignore
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker