tasks:
- name: docker-install
  init: |
    docker-compose pull
    gp sync-done docker
  command: |
    docker-compose up

- name: wordpress-install
  # Waits a little and then configures Wordpress
  init: |
    gp sync-await docker
    echo "Waiting 15s for DB to get ready..."
    sleep 15
    docker exec -it gitpod-wordpress-development-wordpress-1 wp core install --url="8000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}" --title="Gitpod Wordpress Development" --admin_user="admin" --admin_password="admin" --admin_email="you@example.com" --allow-root
    gp preview $(gp url 8000) --external

ports:
  - port: 8000
    onOpen: ignore
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker