tasks:
- name: docker-install
  init: |
    docker-compose pull
  command: |
    docker-compose up

- name: wordpress-install
  init: |
    ./db-check.sh
    docker exec -it gitpod-wordpress-development-wordpress-1 wp core install --url="8000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}" --title="Gitpod Wordpress Development" --admin_user="admin" --admin_password="admin" --admin_email="you@example.com" --allow-root

ports:
  - port: 8000
    onOpen: open-preview
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker