services:
  db:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
  
  wordpress:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: wp-dockerfile #contains WP-CLI
    ports:
      - '8000:80'
    restart: always
    volumes: 
      - ./wp-core:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      
volumes:
  db-data:
  wp-plugins:
    driver_opts:
      type: none
      device: ${PWD}/wp-core
      o: bind,uid=33333,gid=33333