services:
  db:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: unless-stopped
    volumes: 
      - ../wp-core:/var/www/html
      - ../wp-content/themes:/var/www/html/wp-content/themes
      - ../wp-content/plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        // Dynamic URL configuration for WordPress
        // This handles both localhost development and GitHub Codespaces environments
        if (getenv('CODESPACES') === 'true') {
          // GitHub Codespaces environment
          $$codespace_name = getenv('CODESPACE_NAME');
          $$forwarding_domain = getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN');
          if ($$codespace_name && $$forwarding_domain) {
            $$site_url = "https://{$$codespace_name}-80.{$$forwarding_domain}";
            define('WP_HOME', $$site_url);
            define('WP_SITEURL', $$site_url);
          }
        } else {
          // Local development environment
          define('WP_HOME', 'http://localhost:8080');
          define('WP_SITEURL', 'http://localhost:8080');
        }

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      
volumes:
  db-data:
